Random
chubin/cheat.sh pull request #248
Opened 2020-11-07 20:23 UTC by fedebuonco

2020-11-09 15:25 UTC, chubin requested changes
If I understand it right, you just rewrite `/:random` query in a randomly selected page name, instead of resolving the request. Interesting approach, and I think we can try to with it.

Could you please fix these minor things,
+ add spaces after commas (`,`),
+ make `if`-s and their actions on separate lines?

2020-11-09 15:25 UTC, chubin commented on README.md
> +notnot
What is this?

2020-11-09 15:25 UTC, chubin commented on lib/routing.py
> +            if ":list" in topic_list: topic_list.remove(":list")
You should remove all queries starting with `:`, and containing `:` instead

2020-11-09 17:28 UTC, fedebuonco commented on README.md
> +notnot
It is an error, will remove it.

2020-11-09 17:44 UTC, fedebuonco commented on lib/routing.py
> +            if ":list" in topic_list: topic_list.remove(":list")
Shouldn't be removing all the queries containing `:` be sufficient? It will also cover the query starting with `:` .

2020-11-10 09:21 UTC, chubin commented on lib/routing.py
> +            if ":list" in topic_list: topic_list.remove(":list")
Sorry, it was a typo. I meant "containing `/`"

2020-11-10 09:24 UTC, chubin commented on lib/routing.py
> +            if ":list" in topic_list: topic_list.remove(":list")
For the moment, there are no cheat sheets containing `:` in the name, but in future it may be used to define namespace. For example, you have several cheat sheets with the same name (say `ls`) in different cheat sheet sources, but you want to have the one that comes from `tldr`. In this case you can use `tldr:ls`. It is not implemented yet, though.
Such names will not be shown in `/:list` anyway, and so they are probably irrelevant for you. So you can safely drop all pages containing `:`

2020-11-10 10:19 UTC, fedebuonco commented on lib/routing.py
> +            if ":list" in topic_list: topic_list.remove(":list")
Ok, done.

2020-11-13 07:31 UTC, merged

2020-11-13 07:33 UTC, chubin commented
Tested, merged, deployed. It works!

Could you please mention `:random` in `/:help`?